-- Sample Data for Food Delivery App
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('Biryani House', 'TestCity', 4.5, 30, 0, '20% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('Pizza Corner', 'TestCity', 4.2, 45, 0, 'Buy 1 Get 1');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('Green Leaf Veg', 'TestCity', 4.8, 20, 1, 'Free Dessert');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('Spicy Wok', 'TestCity', 4.1, 40, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('Urban Burger', 'TestCity', 4.6, 25, 0, 'Free Fries');

-- Menu Items for Biryani House (restaurant_id = 1)
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (1, 'Chicken Biryani', 250.00, 'Aromatic basmati rice cooked with tender chicken pieces', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (1, 'Mutton Biryani', 350.00, 'Rich and flavorful mutton biryani', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (1, 'Veg Biryani', 200.00, 'Delicious vegetable biryani with paneer', 1);

-- Menu Items for Pizza Corner (restaurant_id = 2)
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (2, 'Margherita Pizza', 300.00, 'Classic cheese pizza', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (2, 'Pepperoni Pizza', 400.00, 'Loaded with pepperoni', 0);

-- Menu Items for Green Leaf Veg (restaurant_id = 3)
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (3, 'Paneer Butter Masala', 220.00, 'Rich paneer curry', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (3, 'Dal Makhani', 180.00, 'Creamy black lentils', 1);

-- Menu Items for Urban Burger (restaurant_id = 5)
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (5, 'Classic Cheeseburger', 150.00, 'Juicy beef patty with cheese', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (5, 'Veggie Burger', 120.00, 'Crispy veg patty', 1);



-- Generated 30 Restaurants

INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('BENGALORE Restaurant 1', 'BENGALORE', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('BENGALORE Restaurant 2', 'BENGALORE', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('BENGALORE Restaurant 3', 'BENGALORE', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('BENGALORE Restaurant 4', 'BENGALORE', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('BENGALORE Restaurant 5', 'BENGALORE', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('BENGALORE Restaurant 6', 'BENGALORE', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('BENGALORE Restaurant 7', 'BENGALORE', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('BENGALORE Restaurant 8', 'BENGALORE', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('BENGALORE Restaurant 9', 'BENGALORE', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('BENGALORE Restaurant 10', 'BENGALORE', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('DELHI Restaurant 1', 'DELHI', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('DELHI Restaurant 2', 'DELHI', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('DELHI Restaurant 3', 'DELHI', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('DELHI Restaurant 4', 'DELHI', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('DELHI Restaurant 5', 'DELHI', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('DELHI Restaurant 6', 'DELHI', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('DELHI Restaurant 7', 'DELHI', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('DELHI Restaurant 8', 'DELHI', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('DELHI Restaurant 9', 'DELHI', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('DELHI Restaurant 10', 'DELHI', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('HYDERABAD Restaurant 1', 'HYDERABAD', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('HYDERABAD Restaurant 2', 'HYDERABAD', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('HYDERABAD Restaurant 3', 'HYDERABAD', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('HYDERABAD Restaurant 4', 'HYDERABAD', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('HYDERABAD Restaurant 5', 'HYDERABAD', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('HYDERABAD Restaurant 6', 'HYDERABAD', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('HYDERABAD Restaurant 7', 'HYDERABAD', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('HYDERABAD Restaurant 8', 'HYDERABAD', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('HYDERABAD Restaurant 9', 'HYDERABAD', 4.2, 30, 0, '10% OFF');
INSERT INTO Restaurants (name, city, rating, delivery_time, is_veg_only, offers) VALUES ('HYDERABAD Restaurant 10', 'HYDERABAD', 4.2, 30, 0, '10% OFF');

-- Generated Menu Items

INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (6, 'Item 1 at Rest 1 in BENGALORE', 110, 'Delicious Item 1 at Rest 1 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (6, 'Item 2 at Rest 1 in BENGALORE', 120, 'Delicious Item 2 at Rest 1 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (6, 'Item 3 at Rest 1 in BENGALORE', 130, 'Delicious Item 3 at Rest 1 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (6, 'Item 4 at Rest 1 in BENGALORE', 140, 'Delicious Item 4 at Rest 1 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (6, 'Item 5 at Rest 1 in BENGALORE', 150, 'Delicious Item 5 at Rest 1 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (6, 'Item 6 at Rest 1 in BENGALORE', 160, 'Delicious Item 6 at Rest 1 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (6, 'Item 7 at Rest 1 in BENGALORE', 170, 'Delicious Item 7 at Rest 1 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (6, 'Item 8 at Rest 1 in BENGALORE', 180, 'Delicious Item 8 at Rest 1 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (6, 'Item 9 at Rest 1 in BENGALORE', 190, 'Delicious Item 9 at Rest 1 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (6, 'Item 10 at Rest 1 in BENGALORE', 200, 'Delicious Item 10 at Rest 1 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (7, 'Item 1 at Rest 2 in BENGALORE', 110, 'Delicious Item 1 at Rest 2 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (7, 'Item 2 at Rest 2 in BENGALORE', 120, 'Delicious Item 2 at Rest 2 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (7, 'Item 3 at Rest 2 in BENGALORE', 130, 'Delicious Item 3 at Rest 2 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (7, 'Item 4 at Rest 2 in BENGALORE', 140, 'Delicious Item 4 at Rest 2 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (7, 'Item 5 at Rest 2 in BENGALORE', 150, 'Delicious Item 5 at Rest 2 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (7, 'Item 6 at Rest 2 in BENGALORE', 160, 'Delicious Item 6 at Rest 2 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (7, 'Item 7 at Rest 2 in BENGALORE', 170, 'Delicious Item 7 at Rest 2 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (7, 'Item 8 at Rest 2 in BENGALORE', 180, 'Delicious Item 8 at Rest 2 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (7, 'Item 9 at Rest 2 in BENGALORE', 190, 'Delicious Item 9 at Rest 2 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (7, 'Item 10 at Rest 2 in BENGALORE', 200, 'Delicious Item 10 at Rest 2 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (8, 'Item 1 at Rest 3 in BENGALORE', 110, 'Delicious Item 1 at Rest 3 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (8, 'Item 2 at Rest 3 in BENGALORE', 120, 'Delicious Item 2 at Rest 3 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (8, 'Item 3 at Rest 3 in BENGALORE', 130, 'Delicious Item 3 at Rest 3 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (8, 'Item 4 at Rest 3 in BENGALORE', 140, 'Delicious Item 4 at Rest 3 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (8, 'Item 5 at Rest 3 in BENGALORE', 150, 'Delicious Item 5 at Rest 3 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (8, 'Item 6 at Rest 3 in BENGALORE', 160, 'Delicious Item 6 at Rest 3 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (8, 'Item 7 at Rest 3 in BENGALORE', 170, 'Delicious Item 7 at Rest 3 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (8, 'Item 8 at Rest 3 in BENGALORE', 180, 'Delicious Item 8 at Rest 3 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (8, 'Item 9 at Rest 3 in BENGALORE', 190, 'Delicious Item 9 at Rest 3 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (8, 'Item 10 at Rest 3 in BENGALORE', 200, 'Delicious Item 10 at Rest 3 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (9, 'Item 1 at Rest 4 in BENGALORE', 110, 'Delicious Item 1 at Rest 4 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (9, 'Item 2 at Rest 4 in BENGALORE', 120, 'Delicious Item 2 at Rest 4 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (9, 'Item 3 at Rest 4 in BENGALORE', 130, 'Delicious Item 3 at Rest 4 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (9, 'Item 4 at Rest 4 in BENGALORE', 140, 'Delicious Item 4 at Rest 4 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (9, 'Item 5 at Rest 4 in BENGALORE', 150, 'Delicious Item 5 at Rest 4 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (9, 'Item 6 at Rest 4 in BENGALORE', 160, 'Delicious Item 6 at Rest 4 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (9, 'Item 7 at Rest 4 in BENGALORE', 170, 'Delicious Item 7 at Rest 4 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (9, 'Item 8 at Rest 4 in BENGALORE', 180, 'Delicious Item 8 at Rest 4 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (9, 'Item 9 at Rest 4 in BENGALORE', 190, 'Delicious Item 9 at Rest 4 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (9, 'Item 10 at Rest 4 in BENGALORE', 200, 'Delicious Item 10 at Rest 4 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (10, 'Item 1 at Rest 5 in BENGALORE', 110, 'Delicious Item 1 at Rest 5 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (10, 'Item 2 at Rest 5 in BENGALORE', 120, 'Delicious Item 2 at Rest 5 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (10, 'Item 3 at Rest 5 in BENGALORE', 130, 'Delicious Item 3 at Rest 5 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (10, 'Item 4 at Rest 5 in BENGALORE', 140, 'Delicious Item 4 at Rest 5 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (10, 'Item 5 at Rest 5 in BENGALORE', 150, 'Delicious Item 5 at Rest 5 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (10, 'Item 6 at Rest 5 in BENGALORE', 160, 'Delicious Item 6 at Rest 5 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (10, 'Item 7 at Rest 5 in BENGALORE', 170, 'Delicious Item 7 at Rest 5 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (10, 'Item 8 at Rest 5 in BENGALORE', 180, 'Delicious Item 8 at Rest 5 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (10, 'Item 9 at Rest 5 in BENGALORE', 190, 'Delicious Item 9 at Rest 5 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (10, 'Item 10 at Rest 5 in BENGALORE', 200, 'Delicious Item 10 at Rest 5 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (11, 'Item 1 at Rest 6 in BENGALORE', 110, 'Delicious Item 1 at Rest 6 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (11, 'Item 2 at Rest 6 in BENGALORE', 120, 'Delicious Item 2 at Rest 6 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (11, 'Item 3 at Rest 6 in BENGALORE', 130, 'Delicious Item 3 at Rest 6 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (11, 'Item 4 at Rest 6 in BENGALORE', 140, 'Delicious Item 4 at Rest 6 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (11, 'Item 5 at Rest 6 in BENGALORE', 150, 'Delicious Item 5 at Rest 6 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (11, 'Item 6 at Rest 6 in BENGALORE', 160, 'Delicious Item 6 at Rest 6 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (11, 'Item 7 at Rest 6 in BENGALORE', 170, 'Delicious Item 7 at Rest 6 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (11, 'Item 8 at Rest 6 in BENGALORE', 180, 'Delicious Item 8 at Rest 6 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (11, 'Item 9 at Rest 6 in BENGALORE', 190, 'Delicious Item 9 at Rest 6 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (11, 'Item 10 at Rest 6 in BENGALORE', 200, 'Delicious Item 10 at Rest 6 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (12, 'Item 1 at Rest 7 in BENGALORE', 110, 'Delicious Item 1 at Rest 7 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (12, 'Item 2 at Rest 7 in BENGALORE', 120, 'Delicious Item 2 at Rest 7 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (12, 'Item 3 at Rest 7 in BENGALORE', 130, 'Delicious Item 3 at Rest 7 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (12, 'Item 4 at Rest 7 in BENGALORE', 140, 'Delicious Item 4 at Rest 7 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (12, 'Item 5 at Rest 7 in BENGALORE', 150, 'Delicious Item 5 at Rest 7 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (12, 'Item 6 at Rest 7 in BENGALORE', 160, 'Delicious Item 6 at Rest 7 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (12, 'Item 7 at Rest 7 in BENGALORE', 170, 'Delicious Item 7 at Rest 7 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (12, 'Item 8 at Rest 7 in BENGALORE', 180, 'Delicious Item 8 at Rest 7 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (12, 'Item 9 at Rest 7 in BENGALORE', 190, 'Delicious Item 9 at Rest 7 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (12, 'Item 10 at Rest 7 in BENGALORE', 200, 'Delicious Item 10 at Rest 7 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (13, 'Item 1 at Rest 8 in BENGALORE', 110, 'Delicious Item 1 at Rest 8 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (13, 'Item 2 at Rest 8 in BENGALORE', 120, 'Delicious Item 2 at Rest 8 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (13, 'Item 3 at Rest 8 in BENGALORE', 130, 'Delicious Item 3 at Rest 8 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (13, 'Item 4 at Rest 8 in BENGALORE', 140, 'Delicious Item 4 at Rest 8 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (13, 'Item 5 at Rest 8 in BENGALORE', 150, 'Delicious Item 5 at Rest 8 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (13, 'Item 6 at Rest 8 in BENGALORE', 160, 'Delicious Item 6 at Rest 8 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (13, 'Item 7 at Rest 8 in BENGALORE', 170, 'Delicious Item 7 at Rest 8 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (13, 'Item 8 at Rest 8 in BENGALORE', 180, 'Delicious Item 8 at Rest 8 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (13, 'Item 9 at Rest 8 in BENGALORE', 190, 'Delicious Item 9 at Rest 8 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (13, 'Item 10 at Rest 8 in BENGALORE', 200, 'Delicious Item 10 at Rest 8 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (14, 'Item 1 at Rest 9 in BENGALORE', 110, 'Delicious Item 1 at Rest 9 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (14, 'Item 2 at Rest 9 in BENGALORE', 120, 'Delicious Item 2 at Rest 9 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (14, 'Item 3 at Rest 9 in BENGALORE', 130, 'Delicious Item 3 at Rest 9 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (14, 'Item 4 at Rest 9 in BENGALORE', 140, 'Delicious Item 4 at Rest 9 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (14, 'Item 5 at Rest 9 in BENGALORE', 150, 'Delicious Item 5 at Rest 9 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (14, 'Item 6 at Rest 9 in BENGALORE', 160, 'Delicious Item 6 at Rest 9 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (14, 'Item 7 at Rest 9 in BENGALORE', 170, 'Delicious Item 7 at Rest 9 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (14, 'Item 8 at Rest 9 in BENGALORE', 180, 'Delicious Item 8 at Rest 9 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (14, 'Item 9 at Rest 9 in BENGALORE', 190, 'Delicious Item 9 at Rest 9 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (14, 'Item 10 at Rest 9 in BENGALORE', 200, 'Delicious Item 10 at Rest 9 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (15, 'Item 1 at Rest 10 in BENGALORE', 110, 'Delicious Item 1 at Rest 10 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (15, 'Item 2 at Rest 10 in BENGALORE', 120, 'Delicious Item 2 at Rest 10 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (15, 'Item 3 at Rest 10 in BENGALORE', 130, 'Delicious Item 3 at Rest 10 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (15, 'Item 4 at Rest 10 in BENGALORE', 140, 'Delicious Item 4 at Rest 10 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (15, 'Item 5 at Rest 10 in BENGALORE', 150, 'Delicious Item 5 at Rest 10 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (15, 'Item 6 at Rest 10 in BENGALORE', 160, 'Delicious Item 6 at Rest 10 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (15, 'Item 7 at Rest 10 in BENGALORE', 170, 'Delicious Item 7 at Rest 10 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (15, 'Item 8 at Rest 10 in BENGALORE', 180, 'Delicious Item 8 at Rest 10 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (15, 'Item 9 at Rest 10 in BENGALORE', 190, 'Delicious Item 9 at Rest 10 in BENGALORE', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (15, 'Item 10 at Rest 10 in BENGALORE', 200, 'Delicious Item 10 at Rest 10 in BENGALORE', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (16, 'Item 1 at Rest 1 in DELHI', 110, 'Delicious Item 1 at Rest 1 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (16, 'Item 2 at Rest 1 in DELHI', 120, 'Delicious Item 2 at Rest 1 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (16, 'Item 3 at Rest 1 in DELHI', 130, 'Delicious Item 3 at Rest 1 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (16, 'Item 4 at Rest 1 in DELHI', 140, 'Delicious Item 4 at Rest 1 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (16, 'Item 5 at Rest 1 in DELHI', 150, 'Delicious Item 5 at Rest 1 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (16, 'Item 6 at Rest 1 in DELHI', 160, 'Delicious Item 6 at Rest 1 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (16, 'Item 7 at Rest 1 in DELHI', 170, 'Delicious Item 7 at Rest 1 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (16, 'Item 8 at Rest 1 in DELHI', 180, 'Delicious Item 8 at Rest 1 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (16, 'Item 9 at Rest 1 in DELHI', 190, 'Delicious Item 9 at Rest 1 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (16, 'Item 10 at Rest 1 in DELHI', 200, 'Delicious Item 10 at Rest 1 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (17, 'Item 1 at Rest 2 in DELHI', 110, 'Delicious Item 1 at Rest 2 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (17, 'Item 2 at Rest 2 in DELHI', 120, 'Delicious Item 2 at Rest 2 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (17, 'Item 3 at Rest 2 in DELHI', 130, 'Delicious Item 3 at Rest 2 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (17, 'Item 4 at Rest 2 in DELHI', 140, 'Delicious Item 4 at Rest 2 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (17, 'Item 5 at Rest 2 in DELHI', 150, 'Delicious Item 5 at Rest 2 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (17, 'Item 6 at Rest 2 in DELHI', 160, 'Delicious Item 6 at Rest 2 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (17, 'Item 7 at Rest 2 in DELHI', 170, 'Delicious Item 7 at Rest 2 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (17, 'Item 8 at Rest 2 in DELHI', 180, 'Delicious Item 8 at Rest 2 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (17, 'Item 9 at Rest 2 in DELHI', 190, 'Delicious Item 9 at Rest 2 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (17, 'Item 10 at Rest 2 in DELHI', 200, 'Delicious Item 10 at Rest 2 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (18, 'Item 1 at Rest 3 in DELHI', 110, 'Delicious Item 1 at Rest 3 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (18, 'Item 2 at Rest 3 in DELHI', 120, 'Delicious Item 2 at Rest 3 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (18, 'Item 3 at Rest 3 in DELHI', 130, 'Delicious Item 3 at Rest 3 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (18, 'Item 4 at Rest 3 in DELHI', 140, 'Delicious Item 4 at Rest 3 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (18, 'Item 5 at Rest 3 in DELHI', 150, 'Delicious Item 5 at Rest 3 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (18, 'Item 6 at Rest 3 in DELHI', 160, 'Delicious Item 6 at Rest 3 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (18, 'Item 7 at Rest 3 in DELHI', 170, 'Delicious Item 7 at Rest 3 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (18, 'Item 8 at Rest 3 in DELHI', 180, 'Delicious Item 8 at Rest 3 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (18, 'Item 9 at Rest 3 in DELHI', 190, 'Delicious Item 9 at Rest 3 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (18, 'Item 10 at Rest 3 in DELHI', 200, 'Delicious Item 10 at Rest 3 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (19, 'Item 1 at Rest 4 in DELHI', 110, 'Delicious Item 1 at Rest 4 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (19, 'Item 2 at Rest 4 in DELHI', 120, 'Delicious Item 2 at Rest 4 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (19, 'Item 3 at Rest 4 in DELHI', 130, 'Delicious Item 3 at Rest 4 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (19, 'Item 4 at Rest 4 in DELHI', 140, 'Delicious Item 4 at Rest 4 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (19, 'Item 5 at Rest 4 in DELHI', 150, 'Delicious Item 5 at Rest 4 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (19, 'Item 6 at Rest 4 in DELHI', 160, 'Delicious Item 6 at Rest 4 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (19, 'Item 7 at Rest 4 in DELHI', 170, 'Delicious Item 7 at Rest 4 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (19, 'Item 8 at Rest 4 in DELHI', 180, 'Delicious Item 8 at Rest 4 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (19, 'Item 9 at Rest 4 in DELHI', 190, 'Delicious Item 9 at Rest 4 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (19, 'Item 10 at Rest 4 in DELHI', 200, 'Delicious Item 10 at Rest 4 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (20, 'Item 1 at Rest 5 in DELHI', 110, 'Delicious Item 1 at Rest 5 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (20, 'Item 2 at Rest 5 in DELHI', 120, 'Delicious Item 2 at Rest 5 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (20, 'Item 3 at Rest 5 in DELHI', 130, 'Delicious Item 3 at Rest 5 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (20, 'Item 4 at Rest 5 in DELHI', 140, 'Delicious Item 4 at Rest 5 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (20, 'Item 5 at Rest 5 in DELHI', 150, 'Delicious Item 5 at Rest 5 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (20, 'Item 6 at Rest 5 in DELHI', 160, 'Delicious Item 6 at Rest 5 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (20, 'Item 7 at Rest 5 in DELHI', 170, 'Delicious Item 7 at Rest 5 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (20, 'Item 8 at Rest 5 in DELHI', 180, 'Delicious Item 8 at Rest 5 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (20, 'Item 9 at Rest 5 in DELHI', 190, 'Delicious Item 9 at Rest 5 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (20, 'Item 10 at Rest 5 in DELHI', 200, 'Delicious Item 10 at Rest 5 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (21, 'Item 1 at Rest 6 in DELHI', 110, 'Delicious Item 1 at Rest 6 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (21, 'Item 2 at Rest 6 in DELHI', 120, 'Delicious Item 2 at Rest 6 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (21, 'Item 3 at Rest 6 in DELHI', 130, 'Delicious Item 3 at Rest 6 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (21, 'Item 4 at Rest 6 in DELHI', 140, 'Delicious Item 4 at Rest 6 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (21, 'Item 5 at Rest 6 in DELHI', 150, 'Delicious Item 5 at Rest 6 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (21, 'Item 6 at Rest 6 in DELHI', 160, 'Delicious Item 6 at Rest 6 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (21, 'Item 7 at Rest 6 in DELHI', 170, 'Delicious Item 7 at Rest 6 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (21, 'Item 8 at Rest 6 in DELHI', 180, 'Delicious Item 8 at Rest 6 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (21, 'Item 9 at Rest 6 in DELHI', 190, 'Delicious Item 9 at Rest 6 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (21, 'Item 10 at Rest 6 in DELHI', 200, 'Delicious Item 10 at Rest 6 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (22, 'Item 1 at Rest 7 in DELHI', 110, 'Delicious Item 1 at Rest 7 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (22, 'Item 2 at Rest 7 in DELHI', 120, 'Delicious Item 2 at Rest 7 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (22, 'Item 3 at Rest 7 in DELHI', 130, 'Delicious Item 3 at Rest 7 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (22, 'Item 4 at Rest 7 in DELHI', 140, 'Delicious Item 4 at Rest 7 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (22, 'Item 5 at Rest 7 in DELHI', 150, 'Delicious Item 5 at Rest 7 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (22, 'Item 6 at Rest 7 in DELHI', 160, 'Delicious Item 6 at Rest 7 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (22, 'Item 7 at Rest 7 in DELHI', 170, 'Delicious Item 7 at Rest 7 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (22, 'Item 8 at Rest 7 in DELHI', 180, 'Delicious Item 8 at Rest 7 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (22, 'Item 9 at Rest 7 in DELHI', 190, 'Delicious Item 9 at Rest 7 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (22, 'Item 10 at Rest 7 in DELHI', 200, 'Delicious Item 10 at Rest 7 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (23, 'Item 1 at Rest 8 in DELHI', 110, 'Delicious Item 1 at Rest 8 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (23, 'Item 2 at Rest 8 in DELHI', 120, 'Delicious Item 2 at Rest 8 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (23, 'Item 3 at Rest 8 in DELHI', 130, 'Delicious Item 3 at Rest 8 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (23, 'Item 4 at Rest 8 in DELHI', 140, 'Delicious Item 4 at Rest 8 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (23, 'Item 5 at Rest 8 in DELHI', 150, 'Delicious Item 5 at Rest 8 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (23, 'Item 6 at Rest 8 in DELHI', 160, 'Delicious Item 6 at Rest 8 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (23, 'Item 7 at Rest 8 in DELHI', 170, 'Delicious Item 7 at Rest 8 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (23, 'Item 8 at Rest 8 in DELHI', 180, 'Delicious Item 8 at Rest 8 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (23, 'Item 9 at Rest 8 in DELHI', 190, 'Delicious Item 9 at Rest 8 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (23, 'Item 10 at Rest 8 in DELHI', 200, 'Delicious Item 10 at Rest 8 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (24, 'Item 1 at Rest 9 in DELHI', 110, 'Delicious Item 1 at Rest 9 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (24, 'Item 2 at Rest 9 in DELHI', 120, 'Delicious Item 2 at Rest 9 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (24, 'Item 3 at Rest 9 in DELHI', 130, 'Delicious Item 3 at Rest 9 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (24, 'Item 4 at Rest 9 in DELHI', 140, 'Delicious Item 4 at Rest 9 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (24, 'Item 5 at Rest 9 in DELHI', 150, 'Delicious Item 5 at Rest 9 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (24, 'Item 6 at Rest 9 in DELHI', 160, 'Delicious Item 6 at Rest 9 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (24, 'Item 7 at Rest 9 in DELHI', 170, 'Delicious Item 7 at Rest 9 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (24, 'Item 8 at Rest 9 in DELHI', 180, 'Delicious Item 8 at Rest 9 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (24, 'Item 9 at Rest 9 in DELHI', 190, 'Delicious Item 9 at Rest 9 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (24, 'Item 10 at Rest 9 in DELHI', 200, 'Delicious Item 10 at Rest 9 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (25, 'Item 1 at Rest 10 in DELHI', 110, 'Delicious Item 1 at Rest 10 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (25, 'Item 2 at Rest 10 in DELHI', 120, 'Delicious Item 2 at Rest 10 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (25, 'Item 3 at Rest 10 in DELHI', 130, 'Delicious Item 3 at Rest 10 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (25, 'Item 4 at Rest 10 in DELHI', 140, 'Delicious Item 4 at Rest 10 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (25, 'Item 5 at Rest 10 in DELHI', 150, 'Delicious Item 5 at Rest 10 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (25, 'Item 6 at Rest 10 in DELHI', 160, 'Delicious Item 6 at Rest 10 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (25, 'Item 7 at Rest 10 in DELHI', 170, 'Delicious Item 7 at Rest 10 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (25, 'Item 8 at Rest 10 in DELHI', 180, 'Delicious Item 8 at Rest 10 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (25, 'Item 9 at Rest 10 in DELHI', 190, 'Delicious Item 9 at Rest 10 in DELHI', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (25, 'Item 10 at Rest 10 in DELHI', 200, 'Delicious Item 10 at Rest 10 in DELHI', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (26, 'Item 1 at Rest 1 in HYDERABAD', 110, 'Delicious Item 1 at Rest 1 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (26, 'Item 2 at Rest 1 in HYDERABAD', 120, 'Delicious Item 2 at Rest 1 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (26, 'Item 3 at Rest 1 in HYDERABAD', 130, 'Delicious Item 3 at Rest 1 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (26, 'Item 4 at Rest 1 in HYDERABAD', 140, 'Delicious Item 4 at Rest 1 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (26, 'Item 5 at Rest 1 in HYDERABAD', 150, 'Delicious Item 5 at Rest 1 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (26, 'Item 6 at Rest 1 in HYDERABAD', 160, 'Delicious Item 6 at Rest 1 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (26, 'Item 7 at Rest 1 in HYDERABAD', 170, 'Delicious Item 7 at Rest 1 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (26, 'Item 8 at Rest 1 in HYDERABAD', 180, 'Delicious Item 8 at Rest 1 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (26, 'Item 9 at Rest 1 in HYDERABAD', 190, 'Delicious Item 9 at Rest 1 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (26, 'Item 10 at Rest 1 in HYDERABAD', 200, 'Delicious Item 10 at Rest 1 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (27, 'Item 1 at Rest 2 in HYDERABAD', 110, 'Delicious Item 1 at Rest 2 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (27, 'Item 2 at Rest 2 in HYDERABAD', 120, 'Delicious Item 2 at Rest 2 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (27, 'Item 3 at Rest 2 in HYDERABAD', 130, 'Delicious Item 3 at Rest 2 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (27, 'Item 4 at Rest 2 in HYDERABAD', 140, 'Delicious Item 4 at Rest 2 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (27, 'Item 5 at Rest 2 in HYDERABAD', 150, 'Delicious Item 5 at Rest 2 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (27, 'Item 6 at Rest 2 in HYDERABAD', 160, 'Delicious Item 6 at Rest 2 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (27, 'Item 7 at Rest 2 in HYDERABAD', 170, 'Delicious Item 7 at Rest 2 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (27, 'Item 8 at Rest 2 in HYDERABAD', 180, 'Delicious Item 8 at Rest 2 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (27, 'Item 9 at Rest 2 in HYDERABAD', 190, 'Delicious Item 9 at Rest 2 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (27, 'Item 10 at Rest 2 in HYDERABAD', 200, 'Delicious Item 10 at Rest 2 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (28, 'Item 1 at Rest 3 in HYDERABAD', 110, 'Delicious Item 1 at Rest 3 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (28, 'Item 2 at Rest 3 in HYDERABAD', 120, 'Delicious Item 2 at Rest 3 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (28, 'Item 3 at Rest 3 in HYDERABAD', 130, 'Delicious Item 3 at Rest 3 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (28, 'Item 4 at Rest 3 in HYDERABAD', 140, 'Delicious Item 4 at Rest 3 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (28, 'Item 5 at Rest 3 in HYDERABAD', 150, 'Delicious Item 5 at Rest 3 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (28, 'Item 6 at Rest 3 in HYDERABAD', 160, 'Delicious Item 6 at Rest 3 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (28, 'Item 7 at Rest 3 in HYDERABAD', 170, 'Delicious Item 7 at Rest 3 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (28, 'Item 8 at Rest 3 in HYDERABAD', 180, 'Delicious Item 8 at Rest 3 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (28, 'Item 9 at Rest 3 in HYDERABAD', 190, 'Delicious Item 9 at Rest 3 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (28, 'Item 10 at Rest 3 in HYDERABAD', 200, 'Delicious Item 10 at Rest 3 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (29, 'Item 1 at Rest 4 in HYDERABAD', 110, 'Delicious Item 1 at Rest 4 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (29, 'Item 2 at Rest 4 in HYDERABAD', 120, 'Delicious Item 2 at Rest 4 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (29, 'Item 3 at Rest 4 in HYDERABAD', 130, 'Delicious Item 3 at Rest 4 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (29, 'Item 4 at Rest 4 in HYDERABAD', 140, 'Delicious Item 4 at Rest 4 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (29, 'Item 5 at Rest 4 in HYDERABAD', 150, 'Delicious Item 5 at Rest 4 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (29, 'Item 6 at Rest 4 in HYDERABAD', 160, 'Delicious Item 6 at Rest 4 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (29, 'Item 7 at Rest 4 in HYDERABAD', 170, 'Delicious Item 7 at Rest 4 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (29, 'Item 8 at Rest 4 in HYDERABAD', 180, 'Delicious Item 8 at Rest 4 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (29, 'Item 9 at Rest 4 in HYDERABAD', 190, 'Delicious Item 9 at Rest 4 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (29, 'Item 10 at Rest 4 in HYDERABAD', 200, 'Delicious Item 10 at Rest 4 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (30, 'Item 1 at Rest 5 in HYDERABAD', 110, 'Delicious Item 1 at Rest 5 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (30, 'Item 2 at Rest 5 in HYDERABAD', 120, 'Delicious Item 2 at Rest 5 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (30, 'Item 3 at Rest 5 in HYDERABAD', 130, 'Delicious Item 3 at Rest 5 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (30, 'Item 4 at Rest 5 in HYDERABAD', 140, 'Delicious Item 4 at Rest 5 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (30, 'Item 5 at Rest 5 in HYDERABAD', 150, 'Delicious Item 5 at Rest 5 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (30, 'Item 6 at Rest 5 in HYDERABAD', 160, 'Delicious Item 6 at Rest 5 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (30, 'Item 7 at Rest 5 in HYDERABAD', 170, 'Delicious Item 7 at Rest 5 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (30, 'Item 8 at Rest 5 in HYDERABAD', 180, 'Delicious Item 8 at Rest 5 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (30, 'Item 9 at Rest 5 in HYDERABAD', 190, 'Delicious Item 9 at Rest 5 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (30, 'Item 10 at Rest 5 in HYDERABAD', 200, 'Delicious Item 10 at Rest 5 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (31, 'Item 1 at Rest 6 in HYDERABAD', 110, 'Delicious Item 1 at Rest 6 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (31, 'Item 2 at Rest 6 in HYDERABAD', 120, 'Delicious Item 2 at Rest 6 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (31, 'Item 3 at Rest 6 in HYDERABAD', 130, 'Delicious Item 3 at Rest 6 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (31, 'Item 4 at Rest 6 in HYDERABAD', 140, 'Delicious Item 4 at Rest 6 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (31, 'Item 5 at Rest 6 in HYDERABAD', 150, 'Delicious Item 5 at Rest 6 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (31, 'Item 6 at Rest 6 in HYDERABAD', 160, 'Delicious Item 6 at Rest 6 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (31, 'Item 7 at Rest 6 in HYDERABAD', 170, 'Delicious Item 7 at Rest 6 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (31, 'Item 8 at Rest 6 in HYDERABAD', 180, 'Delicious Item 8 at Rest 6 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (31, 'Item 9 at Rest 6 in HYDERABAD', 190, 'Delicious Item 9 at Rest 6 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (31, 'Item 10 at Rest 6 in HYDERABAD', 200, 'Delicious Item 10 at Rest 6 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (32, 'Item 1 at Rest 7 in HYDERABAD', 110, 'Delicious Item 1 at Rest 7 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (32, 'Item 2 at Rest 7 in HYDERABAD', 120, 'Delicious Item 2 at Rest 7 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (32, 'Item 3 at Rest 7 in HYDERABAD', 130, 'Delicious Item 3 at Rest 7 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (32, 'Item 4 at Rest 7 in HYDERABAD', 140, 'Delicious Item 4 at Rest 7 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (32, 'Item 5 at Rest 7 in HYDERABAD', 150, 'Delicious Item 5 at Rest 7 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (32, 'Item 6 at Rest 7 in HYDERABAD', 160, 'Delicious Item 6 at Rest 7 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (32, 'Item 7 at Rest 7 in HYDERABAD', 170, 'Delicious Item 7 at Rest 7 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (32, 'Item 8 at Rest 7 in HYDERABAD', 180, 'Delicious Item 8 at Rest 7 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (32, 'Item 9 at Rest 7 in HYDERABAD', 190, 'Delicious Item 9 at Rest 7 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (32, 'Item 10 at Rest 7 in HYDERABAD', 200, 'Delicious Item 10 at Rest 7 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (33, 'Item 1 at Rest 8 in HYDERABAD', 110, 'Delicious Item 1 at Rest 8 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (33, 'Item 2 at Rest 8 in HYDERABAD', 120, 'Delicious Item 2 at Rest 8 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (33, 'Item 3 at Rest 8 in HYDERABAD', 130, 'Delicious Item 3 at Rest 8 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (33, 'Item 4 at Rest 8 in HYDERABAD', 140, 'Delicious Item 4 at Rest 8 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (33, 'Item 5 at Rest 8 in HYDERABAD', 150, 'Delicious Item 5 at Rest 8 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (33, 'Item 6 at Rest 8 in HYDERABAD', 160, 'Delicious Item 6 at Rest 8 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (33, 'Item 7 at Rest 8 in HYDERABAD', 170, 'Delicious Item 7 at Rest 8 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (33, 'Item 8 at Rest 8 in HYDERABAD', 180, 'Delicious Item 8 at Rest 8 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (33, 'Item 9 at Rest 8 in HYDERABAD', 190, 'Delicious Item 9 at Rest 8 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (33, 'Item 10 at Rest 8 in HYDERABAD', 200, 'Delicious Item 10 at Rest 8 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (34, 'Item 1 at Rest 9 in HYDERABAD', 110, 'Delicious Item 1 at Rest 9 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (34, 'Item 2 at Rest 9 in HYDERABAD', 120, 'Delicious Item 2 at Rest 9 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (34, 'Item 3 at Rest 9 in HYDERABAD', 130, 'Delicious Item 3 at Rest 9 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (34, 'Item 4 at Rest 9 in HYDERABAD', 140, 'Delicious Item 4 at Rest 9 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (34, 'Item 5 at Rest 9 in HYDERABAD', 150, 'Delicious Item 5 at Rest 9 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (34, 'Item 6 at Rest 9 in HYDERABAD', 160, 'Delicious Item 6 at Rest 9 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (34, 'Item 7 at Rest 9 in HYDERABAD', 170, 'Delicious Item 7 at Rest 9 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (34, 'Item 8 at Rest 9 in HYDERABAD', 180, 'Delicious Item 8 at Rest 9 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (34, 'Item 9 at Rest 9 in HYDERABAD', 190, 'Delicious Item 9 at Rest 9 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (34, 'Item 10 at Rest 9 in HYDERABAD', 200, 'Delicious Item 10 at Rest 9 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (35, 'Item 1 at Rest 10 in HYDERABAD', 110, 'Delicious Item 1 at Rest 10 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (35, 'Item 2 at Rest 10 in HYDERABAD', 120, 'Delicious Item 2 at Rest 10 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (35, 'Item 3 at Rest 10 in HYDERABAD', 130, 'Delicious Item 3 at Rest 10 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (35, 'Item 4 at Rest 10 in HYDERABAD', 140, 'Delicious Item 4 at Rest 10 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (35, 'Item 5 at Rest 10 in HYDERABAD', 150, 'Delicious Item 5 at Rest 10 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (35, 'Item 6 at Rest 10 in HYDERABAD', 160, 'Delicious Item 6 at Rest 10 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (35, 'Item 7 at Rest 10 in HYDERABAD', 170, 'Delicious Item 7 at Rest 10 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (35, 'Item 8 at Rest 10 in HYDERABAD', 180, 'Delicious Item 8 at Rest 10 in HYDERABAD', 1);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (35, 'Item 9 at Rest 10 in HYDERABAD', 190, 'Delicious Item 9 at Rest 10 in HYDERABAD', 0);
INSERT INTO Menu (restaurant_id, name, price, description, is_veg) VALUES (35, 'Item 10 at Rest 10 in HYDERABAD', 200, 'Delicious Item 10 at Rest 10 in HYDERABAD', 1);
